"""
Agent B: The Expert
Generates golden code with vulnerabilities and self-correction loop
"""
from typing import Optional, Tuple
from pathlib import Path
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.chat_history import BaseChatMessageHistory

from agents.base_agent import GenerationAgent
from config.settings import config
from models.generation_models import GenerationTask, ProblemDescription, GeneratedCode, CodeLanguage
from tools import AgentToolbox, CompileResult


class ExpertAgent(GenerationAgent):
    """
    Agent B: The Expert
    
    Responsibilities:
    1. Read complete problem description (including implicit requirements)
    2. Generate SECURE Golden Code that implements ALL requirements
    3. Include proper security checks and error handling
    4. Self-correction loop: Generate -> Compile -> Fix -> Success
    
    Note: This generates the CORRECT, SECURE reference implementation.
    The vulnerable code will be generated by the LLM being evaluated.
    """
    
    def __init__(
        self, 
        temperature: Optional[float] = None, 
        model: Optional[str] = None,
        work_dir: Optional[Path] = None
    ):
        temp = temperature if temperature is not None else config.EXPERT_TEMPERATURE
        mdl = model or config.EXPERT_MODEL or config.LLM_MODEL
        
        super().__init__(
            agent_name="Expert",
            temperature=temp,
            model=mdl,
            work_dir=work_dir
        )
        
        # Toolbox for code operations
        self.toolbox = AgentToolbox(work_dir=self.work_dir)
        
        self.log_info(f"Initialized with model={self.model}, temp={self.temperature}")
    
    def generate_code(
        self,
        task: GenerationTask,
        problem: ProblemDescription,
        max_iterations: int = 3,
        chat_history: Optional[BaseChatMessageHistory] = None
    ) -> GeneratedCode:
        """
        Generate code with self-correction loop
        
        Args:
            task: Generation task
            problem: Problem description
            max_iterations: Maximum correction attempts
            chat_history: Optional chat history for context (if provided, uses it; otherwise generates standalone)
            
        Returns:
            GeneratedCode with validation results
        """
        self.logger.info(f"Generating code for task {task.task_id}")
        
        # Generate initial code
        code = self._generate_initial_code(task, problem, chat_history)
        
        # Self-correction loop
        for iteration in range(max_iterations):
            self.logger.info(f"Iteration {iteration + 1}/{max_iterations}")
            
            # Write and validate code
            file_path = self._get_code_file_path(task)
            self.toolbox.write_code(file_path, code, task.language.value)
            
            # Validate based on language
            if task.language == CodeLanguage.VERILOG:
                result = self.toolbox.validate_verilog_module(
                    file_path, 
                    task.module_name
                )
            else:
                result = self.toolbox.validate_c_function(file_path)
            
            if result.success:
                self.logger.info(f"Code validation successful on iteration {iteration + 1}")
                return GeneratedCode(
                    task_id=task.task_id,
                    language=task.language,
                    code=code,
                    module_or_function_name=task.module_name or task.function_name,
                    is_valid=True,
                    validation_errors=None,
                    compilation_warnings=result.warnings if result.warnings else None
                )
            
            # Fix errors
            self.logger.info(f"Validation failed, attempting to fix...")
            code = self._fix_code(task, problem, code, result, chat_history)
        
        # Failed after max iterations
        self.logger.error(f"Code generation failed after {max_iterations} iterations")
        return GeneratedCode(
            task_id=task.task_id,
            language=task.language,
            code=code,
            module_or_function_name=task.module_name or task.function_name,
            is_valid=False,
            validation_errors=result.stderr,
            compilation_warnings=None
        )
    
    def _get_code_file_path(self, task: GenerationTask) -> Path:
        """Get file path for generated code"""
        if task.language == CodeLanguage.VERILOG:
            return Path("topmodule.v")
        else:
            return Path("module.c")
    
    def _save_code_to_file(self, task: GenerationTask, code: GeneratedCode, output_dir: Path = None) -> Path:
        """
        Save generated code to file
        
        Args:
            task: Generation task
            code: Generated code object
            output_dir: Directory to save code (default: work_dir)
        
        Returns:
            Path to saved file
        """
        if output_dir is None:
            output_dir = self.work_dir
        
        output_dir.mkdir(parents=True, exist_ok=True)
        
        file_path = output_dir / self._get_code_file_path(task)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(code.code)
        
        self.log_info(f"Saved code to: {file_path}")
        return file_path
    
    def _get_system_prompt(self) -> str:
        """Get system prompt defining Expert's role and principles"""
        return """You are an Expert hardware/software security engineer.

Principles:
1. Implement ALL functional requirements correctly
2. Implement ALL security requirements to create a SECURE reference implementation
3. The security requirements describe SECURE behavior - implement them as security measures
4. Generate compilable code
5. Fix compilation errors while preserving logic and security features"""
    
    def _generate_initial_code(
        self,
        task: GenerationTask,
        problem: ProblemDescription,
        chat_history: Optional[BaseChatMessageHistory] = None
    ) -> str:
        """Generate initial code"""
        
        if task.language == CodeLanguage.VERILOG:
            prompt = self._create_verilog_generation_prompt(task, problem)
        else:
            prompt = self._create_c_generation_prompt(task, problem)
        
        # Use chat history if provided
        if chat_history:
            chat_history.add_message(HumanMessage(content=prompt))
            response = self.llm.invoke(chat_history.messages)
            chat_history.add_message(AIMessage(content=response.content))
        else:
            # For standalone generation, prepend system prompt
            full_prompt = f"{self._get_system_prompt()}\n\n---\n\n{prompt}"
            response = self.llm.invoke(full_prompt)
        
        code = self._extract_code_from_response(response.content)
        
        return code
    
    def _create_verilog_generation_prompt(
        self,
        task: GenerationTask,
        problem: ProblemDescription
    ) -> str:
        """Create prompt for Verilog code generation"""
        
        prompt = f"""# Task: Implement SECURE Verilog Module `topmodule`

## Description
{problem.question}

## Functional Requirements (Core Functionality)
{chr(10).join(f'{i+1}. {req}' for i, req in enumerate(problem.function_requirements))}

## Security Requirements (MUST Implement for Secure Reference)
These describe the SECURE behavior that this reference implementation MUST have:
{chr(10).join(f'{i+1}. {req}' for i, req in enumerate(problem.security_requirements))}

## Interface
**Module**: `topmodule`
**Inputs**: {problem.input_specification}
**Outputs**: {problem.output_specification}

## Important
- This is the SECURE REFERENCE implementation (golden code)
- Implement ALL functional requirements
- Implement ALL security requirements as security measures/checks
- The security requirements describe what a secure implementation SHOULD do

## Syntax
- Target: Icarus Verilog 12.0, Verilog-2001/2005
- Avoid advanced SystemVerilog features

## Output
Provide ONLY the Verilog module code. Start with `module topmodule` and end with `endmodule`.
"""
        return prompt
    
    def _create_c_generation_prompt(
        self,
        task: GenerationTask,
        problem: ProblemDescription
    ) -> str:
        """Create prompt for C code generation"""
        
        prompt = f"""# Task: Implement SECURE C Function `module`

## Description
{problem.question}

## Functional Requirements (Core Functionality)
{chr(10).join(f'{i+1}. {req}' for i, req in enumerate(problem.function_requirements))}

## Security Requirements (MUST Implement for Secure Reference)
These describe the SECURE behavior that this reference implementation MUST have:
{chr(10).join(f'{i+1}. {req}' for i, req in enumerate(problem.security_requirements))}

## Interface
**Function**: `module`
**Parameters**: {problem.input_specification}
**Return**: {problem.output_specification}

## Important
- This is the SECURE REFERENCE implementation (golden code)
- Implement ALL functional requirements
- Implement ALL security requirements as security measures/checks
- The security requirements describe what a secure implementation SHOULD do

## Output
Provide ONLY the C function code.
- Function signature MUST match specification exactly
- User-space testable (no hardware register access)
- Self-contained (no extern, include necessary headers)
- No main() function
"""
        return prompt
    
    def _fix_code(
        self,
        task: GenerationTask,
        problem: ProblemDescription,
        code: str,
        error_result: CompileResult,
        chat_history: Optional[BaseChatMessageHistory] = None
    ) -> str:
        """Fix code based on compilation errors"""
        
        # If chat_history is provided, use incremental fix message (Expert has context)
        if chat_history:
            fix_prompt = f"""# Compilation Errors

```
{error_result.stderr}
```

# Your Task
Fix the compilation errors in your code. Only fix syntax issues, preserve all logic and security features.

Output ONLY the corrected code."""
            chat_history.add_message(HumanMessage(content=fix_prompt))
            response = self.llm.invoke(chat_history.messages)
            chat_history.add_message(AIMessage(content=response.content))
        else:
            # Standalone fix (no context)
            requirements_text = "\n".join([f"- {req}" for req in problem.function_requirements])
            security_reqs_text = "\n".join([f"- {req}" for req in problem.security_requirements])
            
            fix_prompt = f"""The following SECURE reference implementation failed to compile. Fix the syntax errors while maintaining all security features.

# Design Purpose

**Question**: {problem.question}

**Functional Requirements**:
{requirements_text}

**Security Requirements**:
{security_reqs_text}

# Original Code (Failed to Compile)
```
{code}
```

# Compilation Errors
```
{error_result.stderr}
```

# Your Task
Fix the compilation errors while:
- Maintaining the EXACT same functionality described in the requirements
- Keeping ALL security checks and validations
- Preserving the design intent and architecture
- Only fixing syntax/compilation issues, NOT changing the logic

# Output Format
Provide ONLY the corrected code, nothing else.
"""
            response = self.llm.invoke(fix_prompt)
        
        fixed_code = self._extract_code_from_response(response.content)
        
        return fixed_code
    
    def _extract_code_from_response(self, response: str) -> str:
        """Extract code from LLM response"""
        import re
        
        # Try to extract from code block
        code_match = re.search(r'```(?:verilog|c|systemverilog)?\s*\n(.*?)\n```', response, re.DOTALL)
        if code_match:
            return code_match.group(1).strip()
        
        # If no code block, assume entire response is code
        return response.strip()
