"""
C Function Test Execution Tool

LLM generates complete test code with self-contained PASS/FAIL judgments.
This tool compiles, runs, and checks for FAIL in output.

Output format (same as Verilog):
- [CASE-N] PASS
- [CASE-N] FAIL: <reason>
"""
from typing import Dict, Any
from pathlib import Path
import subprocess
import tempfile
import re


class CFunctionTester:
    """
    Compile and run C test code
    
    Input: Function file + complete test code (generated by LLM)
    Output: Compilation/execution results
    """
    
    def __init__(self, gcc_path: str = "gcc", timeout: int = 5):
        self.gcc_path = gcc_path
        self.timeout = timeout
    
    def run_test(
        self,
        function_file: Path,
        test_code: str
    ) -> Dict[str, Any]:
        """
        Compile and run test code
        
        Args:
            function_file: Path to .c file with function implementation
            test_code: Complete test code with main() function
                       Must output "[CASE-N] PASS" or "[CASE-N] FAIL: reason" format
        
        Returns:
            {
                "compile_success": bool,
                "compile_error": str or None,
                "run_success": bool,
                "run_error": str or None,
                "passed": bool (True if no FAIL detected),
                "raw_stdout": str
            }
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            
            # Write test code
            test_file = tmpdir_path / "test_main.c"
            test_file.write_text(test_code)
            
            # Compile
            exe_file = tmpdir_path / "test_exe"
            compile_result = self._compile(function_file, test_file, exe_file)
            
            if not compile_result["success"]:
                return {
                    "compile_success": False,
                    "compile_error": compile_result["stderr"],
                    "run_success": False,
                    "run_error": None,
                    "results": [],
                    "raw_stdout": ""
                }
            
            # Run
            run_result = self._run_executable(exe_file)
            
            if not run_result["success"]:
                return {
                    "compile_success": True,
                    "compile_error": None,
                    "run_success": False,
                    "run_error": run_result["stderr"],
                    "passed": False,
                    "raw_stdout": run_result["stdout"]
                }
            
            # Check for FAIL in output (same logic as Verilog)
            passed = self._check_pass_fail(run_result["stdout"])
            
            return {
                "compile_success": True,
                "compile_error": None,
                "run_success": True,
                "run_error": None,
                "passed": passed,
                "raw_stdout": run_result["stdout"]
            }
    
    def _compile(
        self,
        function_file: Path,
        test_file: Path,
        exe_file: Path
    ) -> Dict[str, Any]:
        """Compile function and test files with proper process cleanup"""
        import os
        import signal
        
        cmd = [
            self.gcc_path,
            "-Wall", "-Wextra",
            "-o", str(exe_file),
            str(function_file),
            str(test_file)
        ]
        
        process = None
        try:
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                start_new_session=True
            )
            try:
                stdout, stderr = process.communicate(timeout=self.timeout)
                return {
                    "success": process.returncode == 0,
                    "stdout": stdout,
                    "stderr": stderr
                }
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(os.getpgid(process.pid), signal.SIGKILL)
                except ProcessLookupError:
                    pass
                process.wait()
                return {
                    "success": False,
                    "stdout": "",
                    "stderr": "Compilation timeout"
                }
        except Exception as e:
            if process is not None:
                try:
                    os.killpg(os.getpgid(process.pid), signal.SIGKILL)
                except (ProcessLookupError, OSError):
                    pass
                process.wait()
            return {
                "success": False,
                "stdout": "",
                "stderr": str(e)
            }
    
    def _run_executable(self, exe_file: Path) -> Dict[str, Any]:
        """Run compiled executable with proper process cleanup"""
        import os
        import signal as sig_module
        
        process = None
        try:
            process = subprocess.Popen(
                [str(exe_file)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                start_new_session=True
            )
            try:
                stdout, stderr = process.communicate(timeout=self.timeout)
                returncode = process.returncode
                
                # Build detailed error message if failed
                if returncode != 0:
                    error_msg = stderr if stderr else ""
                    if returncode < 0:
                        sig_num = -returncode
                        sig_name = sig_module.Signals(sig_num).name if sig_num < 32 else f"Signal {sig_num}"
                        error_msg = f"Process killed by {sig_name} (code {returncode}). {error_msg}"
                    elif not error_msg:
                        error_msg = f"Process exited with code {returncode}"
                        if stdout:
                            error_msg += f". Partial stdout: {stdout[:200]}"
                else:
                    error_msg = stderr
                
                return {
                    "success": returncode == 0,
                    "stdout": stdout,
                    "stderr": error_msg
                }
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(os.getpgid(process.pid), sig_module.SIGKILL)
                except ProcessLookupError:
                    pass
                process.wait()
                return {
                    "success": False,
                    "stdout": "",
                    "stderr": "Execution timeout"
                }
        except Exception as e:
            if process is not None:
                try:
                    os.killpg(os.getpgid(process.pid), sig_module.SIGKILL)
                except (ProcessLookupError, OSError):
                    pass
                process.wait()
            return {
                "success": False,
                "stdout": "",
                "stderr": str(e)
            }
    
    def _check_pass_fail(self, stdout: str) -> bool:
        """
        Check test output for PASS/FAIL (same logic as Verilog testbench)
        
        Returns True if:
        - At least one [CASE-N] PASS exists
        - No [CASE-N] FAIL exists
        """
        # Check for FAIL patterns
        fail_pattern = r'\[CASE-\d+\]\s*FAIL'
        if re.search(fail_pattern, stdout, re.IGNORECASE):
            return False
        
        # Check for at least one PASS
        pass_pattern = r'\[CASE-\d+\]\s*PASS'
        if re.search(pass_pattern, stdout, re.IGNORECASE):
            return True
        
        # No PASS/FAIL found - treat as failure
        return False
